---
name: Bug report
title: '🐛 Bug that needs to be addressed.'
labels: '🐛 bug'
assignees: 'softwareantics'
projects: 'softwareantics/2'

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a bug report.

  - type: checkboxes
    id: checklist
    label: "Prerequisites"
    description: "Please answer the following questions for yourself before submitting an issue:"
    options:
       - label: "I have verified that I am running the latest version."
         - required: true
        - label: "I have checked the documentation and found no solution."
          - required: true
        - label: "I have ensured that this issue has not been previously filed."
          - required: true
        - label: "I am reporting the issue to the correct repository."
          - required: true

---
