---
name: Bug report
title: '🐛 Bug that needs to be addressed.'
labels: '🐛 bug'
assignees: 'softwareantics'
projects: 'softwareantics/2'

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a bug report.

  - type: textarea
    id: current
    attributes:
      label: "Current Behaviour"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Explain what is currently happening."
---
