---
name: 🐛 Bug Report
description: Report a bug to be fixed.
title: "✨ Bug Report"
labels: ["🐛 Bug"]
projects: ["softwareantics/2"]
assignees:
  - softwareantics

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a bug report.

  - type: textarea
    id: current
    attributes:
      label: "Current Behaviour"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Explain what is currently happening."
---
