---
name: ✨ Feature Request
description: Suggest an idea for a new project feature
title: "✨ New Feature"
labels: ["✨ Feature"]
projects: ["Final Engine"]
assignees:
  - softwareantics
body:
  - type: markdown
    attributes:
      value: |
        "Thanks for taking the time to fill out a feature request!"
  - type: textarea
    id: description
    attributes: 
      label: "Briefly describe the proposed feature."
      placeholder: "Tell us what new feature you'd like implemented"
    validations:
      required: true
    

---
