---
name: ✨ Feature Request
description: Suggest an idea for a new project feature
title: "✨ New Feature"
labels: ["✨ Feature"]
projects: ["Final Engine"]
assignees:
  - softwareantics
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a feature request!
  - type: textarea
    id: description
    attributes: 
      description: "Briefly describe the proposed feature."
      placeholder: "Tell us what new feature you'd like implemented"
    validations:
      required: true
  - type: textarea
    id: justification
    attributes:
      description: "Explain the significance and benefits of adding this feature."
      placeholder: "Tell us why you'd like this feature implemented."
    validations:
      required: true
---
