name: ✅ Build Status Check
run-name: ✅ Build Status Check (${{ github.base_ref }} branch)

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  # FinalEngine.Audio
  build_audio:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Audio dependencies
      run: dotnet restore FinalEngine.Audio/FinalEngine.Audio.csproj

    - name: Build FinalEngine.Audio
      run: dotnet build FinalEngine.Audio/FinalEngine.Audio.csproj --no-restore

  # FinalEngine.Audio.OpenAL
  build_audio_openal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Audio.OpenAL dependencies
      run: dotnet restore FinalEngine.Audio.OpenAL/FinalEngine.Audio.OpenAL.csproj

    - name: Build FinalEngine.Audio.OpenAL
      run: dotnet build FinalEngine.Audio.OpenAL/FinalEngine.Audio.OpenAL.csproj --no-restore

  # FinalEngine.ECS
  build_ecs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.ECS dependencies
      run: dotnet restore FinalEngine.ECS/FinalEngine.ECS.csproj

    - name: Build FinalEngine.ECS
      run: dotnet build FinalEngine.ECS/FinalEngine.ECS.csproj --no-restore

  # FinalEngine.ECS.Components
  build_ecs_components:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.ECS.Components dependencies
      run: dotnet restore FinalEngine.ECS.Components/FinalEngine.ECS.Components.csproj

    - name: Build FinalEngine.ECS.Components
      run: dotnet build FinalEngine.ECS.Components/FinalEngine.ECS.Components.csproj --no-restore

  # FinalEngine.ECS.Systems
  build_ecs_systems:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.ECS.Systems dependencies
      run: dotnet restore FinalEngine.ECS.Systems/FinalEngine.ECS.Systems.csproj

    - name: Build FinalEngine.ECS.Systems
      run: dotnet build FinalEngine.ECS.Systems/FinalEngine.ECS.Systems.csproj --no-restore

  # FinalEngine.Editor.Common
  build_editor_common:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Editor.Common dependencies
      run: dotnet restore FinalEngine.Editor.Common/FinalEngine.Editor.Common.csproj

    - name: Build FinalEngine.Editor.Common
      run: dotnet build FinalEngine.Editor.Common/FinalEngine.Editor.Common.csproj --no-restore

  # FinalEngine.Editor.Desktop
  build_editor_desktop:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Editor.Desktop dependencies
      run: dotnet restore FinalEngine.Editor.Desktop/FinalEngine.Editor.Desktop.csproj

    - name: Build FinalEngine.Editor.Desktop
      run: dotnet build FinalEngine.Editor.Desktop/FinalEngine.Editor.Desktop.csproj --no-restore

  # FinalEngine.Editor.ViewModels
  build_editor_view_models:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Editor.ViewModels dependencies
      run: dotnet restore FinalEngine.Editor.ViewModels/FinalEngine.Editor.ViewModels.csproj

    - name: Build FinalEngine.Editor.ViewModels
      run: dotnet build FinalEngine.Editor.ViewModels/FinalEngine.Editor.ViewModels.csproj --no-restore