name: ✅ Build Status Check
run-name: ✅ Build Status Check (${{ github.base_ref }} branch)

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  # FinalEngine.Audio
  build_audio:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Audio dependencies
      run: dotnet restore ../FinalEngine.Audio/FinalEngine.Audio.csproj

    - name: Build FinalEngine.Audio
      run: dotnet build ../FinalEngine.Audio/FinalEngine.Audio.csproj --no-restore

  # FinalEngine.Audio.OpenAL
  build_audio_openal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore FinalEngine.Audio.OpenAL dependencies
      run: dotnet restore ../FinalEngine.Audio.OpenAL/FinalEngine.Audio.OpenAL.csproj

    - name: Build FinalEngine.Audio.OpenAL
      run: dotnet build ../FinalEngine.Audio.OpenAL/FinalEngine.Audio.OpenAL.csproj --no-restore